"""
Coder Agent hardcoded-secret checker (MongoDB connection strings).

Purpose:
A real, confirmed incident: the Coder Agent's own LLM invented an ad hoc `FALLBACK_MONGODB_URI`
constant (a fake-but-realistic credential, e.g. `mongodb+srv://user:pass@cluster0.example.mongodb
.net/db`) while writing route code -- `lib/mongodb.ts`'s scaffold already reads the real
`process.env.MONGODB_URI` correctly (see workspace_service.NEXTJS_LIB_MONGODB), so nothing in the
generated code ever needed a second connection string, but nothing forbade one either. Security
Agent correctly flagged it as CWE-798, and its own finding report -- quoting the offending line
verbatim as evidence -- is what later caused a real, separate bug (env_uri.py's URI-auto-detection
overwriting a human's real .env.local with this fake credential; see that module's own comment).

This module is the deterministic backstop that should have caught the invented constant BEFORE it
ever reached Security Agent: a hard-gated scan of every planned file for a literal MongoDB
connection-string substring outside the one legitimate place it belongs (.env* files, which are
never planned/generated by the Coder Agent's own code -- .env.example is scaffold-authored with
its own intentional placeholder URI). Same "cheap, regex-based, scoped to planned files only"
idiom as route_checker.py/schema_form_checker.py -- no AST, no false-positive risk from any real
scaffold or generated file, since a literal `mongodb://`/`mongodb+srv://` substring has no
legitimate reason to appear anywhere else.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

_MONGODB_URI_LITERAL_PATTERN = re.compile(r"mongodb(?:\+srv)?://", re.IGNORECASE)


def _is_env_file(path: str) -> bool:
    return Path(path).name.startswith(".env")


def scan_for_hardcoded_mongodb_uri(workspace_root: Path, code_plan_json: dict[str, Any]) -> list[dict[str, str]]:
    """
    Returns [{"file": path, "snippet": line}, ...] for every planned, non-deleted, non-`.env*`
    file containing a literal `mongodb://`/`mongodb+srv://` substring -- the one and only
    connection mechanism (`lib/mongodb.ts`'s `process.env.MONGODB_URI` read) never contains this
    literal itself, so any real match here is a genuine hardcoded-connection-string finding.
    """
    findings: list[dict[str, str]] = []

    for file_entry in code_plan_json.get("files", []) or []:
        if file_entry.get("action") == "delete":
            continue

        path = file_entry.get("path", "")
        if not path or _is_env_file(path):
            continue

        file_path = workspace_root / path
        if not file_path.exists() or not file_path.is_file():
            continue

        try:
            content = file_path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue

        for line_number, line in enumerate(content.splitlines(), start=1):
            if _MONGODB_URI_LITERAL_PATTERN.search(line):
                findings.append({"file": path, "line": str(line_number), "snippet": line.strip()})

    return findings
