"""
Requirement Agent Markdown Builder.

Purpose:
This file converts Requirement Agent SRS JSON into human-readable Markdown.

Why this file exists:
- The LLM should generate only JSON to avoid parsing errors.
- Markdown is generated safely by backend Python code.
- This avoids changing shared/common files.
- This keeps Requirement Agent formatting isolated from other agents.

Other agents should create their own markdown builders later, for example:
- domain_agent/markdown_builder.py
- architecture_agent/markdown_builder.py
"""

from typing import Any


class RequirementSRSMarkdownBuilder:
    """
    Converts SRS JSON into SRS Markdown.

    This class belongs only to the Requirement Agent.
    It should not be used by Domain Agent or Architecture Agent.
    """
    def _revision_metadata_section(self, srs_json: dict[str, Any]) -> str:
        """
        Build revision metadata section if the SRS was revised.

        This section appears only when revision_metadata exists.
        """

        revision_metadata = srs_json.get("revision_metadata")

        if not revision_metadata:
            return ""

        return f"""
---

## Revision Metadata

- **Revision Type:** {revision_metadata.get("revision_type", "srs_revision")}
- **Revised By:** {revision_metadata.get("revised_by", "N/A")}
- **Revision Comment:** {revision_metadata.get("revision_comment", "N/A")}
"""
    def build(self, srs_json: dict[str, Any]) -> str:
        """
        Build the full SRS Markdown document from structured SRS JSON.
        """

        return f"""# Software Requirements Specification: {srs_json.get("feature_name", "Untitled Feature")}

## 1. Project Information

- **Project ID:** {srs_json.get("project_id", "N/A")}
- **Project Name:** {srs_json.get("project_name", "N/A")}
- **Project Type:** {srs_json.get("project_type", "N/A")}
- **Feature ID:** {srs_json.get("feature_id", "N/A")}
- **Feature Name:** {srs_json.get("feature_name", "N/A")}
- **Target Stack:** {srs_json.get("target_stack", "Next.js")}
- **Preferred Architectural Style:** {srs_json.get("architectural_style", "modular")}

---

## 2. Business Goal

{srs_json.get("business_goal", "Not specified.")}

---

## 3. Scope

{self._simple_list(srs_json.get("scope", []))}

---

## 4. Out of Scope

{self._simple_list(srs_json.get("out_of_scope", []))}

---

## 5. User Roles

{self._simple_list(srs_json.get("user_roles", []))}

---

## 6. Functional Requirements

{self._requirement_list(srs_json.get("functional_requirements", []))}

---

## 7. Non-Functional Requirements

{self._requirement_list(srs_json.get("non_functional_requirements", []))}

---

## 8. User Stories

{self._user_story_list(srs_json.get("user_stories", []))}

---

## 9. Acceptance Criteria

{self._requirement_list(srs_json.get("acceptance_criteria", []))}

---

## 10. Input Requirements

{self._simple_list(srs_json.get("input_requirements", []))}

---

## 11. Output Requirements

{self._simple_list(srs_json.get("output_requirements", []))}

---

## 12. UI Expectations

{self._simple_list(srs_json.get("ui_expectations", []))}

---

## 13. API Expectations

{self._simple_list(srs_json.get("api_expectations", []))}

---

## 14. Data Requirements

{self._simple_list(srs_json.get("data_requirements", []))}

---

## 15. Validation Rules

{self._requirement_list(srs_json.get("validation_rules", []))}

---

## 16. Constraints

{self._simple_list(srs_json.get("constraints", []))}

---

## 17. Assumptions

{self._simple_list(srs_json.get("assumptions", []))}

---

## 18. Risks

{self._simple_list(srs_json.get("risks", []))}

---

## 19. Dependencies

{self._simple_list(srs_json.get("dependencies", []))}

---

## 20. Requirement Traceability Summary

{self._traceability_list(srs_json.get("traceability", []))}
{self._revision_metadata_section(srs_json)}

---

## 21. Human Approval Note

This SRS was generated by the Requirement Agent.

A human reviewer must approve this artifact before it is passed to the Domain Agent.
"""

    def _simple_list(self, items: list[Any]) -> str:
        """
        Convert a simple list into Markdown bullets.
        """
        if not items:
            return "- Not specified."

        return "\n".join(f"- {item}" for item in items)

    def _requirement_list(self, items: list[dict[str, Any]]) -> str:
        """
        Convert requirement dictionaries into Markdown bullets.

        Example:
        {"id": "FR-001", "description": "User can login"}
        """
        if not items:
            return "- Not specified."

        lines = []

        for item in items:
            item_id = item.get("id", "N/A")
            description = item.get("description", "No description provided.")
            priority = item.get("priority")
            category = item.get("category")

            extra = ""

            if priority:
                extra = f" — Priority: {priority}"
            elif category:
                extra = f" — Category: {category}"

            lines.append(f"- **{item_id}**: {description}{extra}")

        return "\n".join(lines)

    def _user_story_list(self, items: list[dict[str, Any]]) -> str:
        """
        Convert user stories into Markdown.
        """
        if not items:
            return "- Not specified."

        lines = []

        for item in items:
            story_id = item.get("id", "N/A")
            role = item.get("role", "user")
            goal = item.get("goal", "use the feature")
            benefit = item.get("benefit", "achieve the business goal")

            lines.append(
                f"- **{story_id}**: As a **{role}**, "
                f"I want to **{goal}**, so that **{benefit}**."
            )

        return "\n".join(lines)

    def _traceability_list(self, items: list[dict[str, Any]]) -> str:
        """
        Convert traceability records into Markdown.
        """
        if not items:
            return "- Not specified."

        lines = []

        for item in items:
            requirement_id = item.get("requirement_id", "N/A")
            related_criteria = item.get("related_acceptance_criteria", [])
            notes = item.get("notes", "")

            if isinstance(related_criteria, list):
                related_text = ", ".join(related_criteria)
            else:
                related_text = str(related_criteria)

            lines.append(
                f"- **{requirement_id}** → Acceptance Criteria: {related_text or 'N/A'}"
            )

            if notes:
                lines.append(f"  - Notes: {notes}")

        return "\n".join(lines)