"""
Requirement Agent Internal Schemas.

Purpose:
These schemas are used inside the Requirement Agent only.

They are different from API request schemas.
API request schemas are usually kept in:
    app/schemas/requirement_schema.py
"""

from pydantic import BaseModel, Field


class RequirementAgentInput(BaseModel):
    """
    Internal input passed into RequirementAgent.

    project:
        Project metadata from store.projects.

    feature:
        Feature metadata from store.features.

    ba_input:
        Structured BA input.

    human_comment:
        Optional comment used for revision.
    """

    project: dict
    feature: dict
    ba_input: dict
    human_comment: str | None = None

class RequirementAgentOutput(BaseModel):
    """
    Internal output returned by RequirementAgent.

    srs_json:
        Machine-readable SRS.

    srs_markdown:
        Human-readable SRS generated by markdown_builder.py.

    raw_llm_output:
        Original LLM output for debugging.
    """

    srs_json: dict
    srs_markdown: str
    raw_llm_output: str

