"""
Architecture Agent Class Diagram PlantUML Builder.

Purpose:
Convert validated class_diagram_json into PlantUML class diagram source.
"""

from __future__ import annotations

import re
from typing import Any


class ArchitectureClassPlantUMLBuilder:
    """
    Converts class_diagram_json into PlantUML source.
    """

    def build(self, class_json: dict[str, Any]) -> str:
        title = class_json.get("diagram_title", "Class Diagram")
        classes = class_json.get("classes", [])
        relationships = class_json.get("relationships", [])

        lines: list[str] = []
        lines.append("@startuml")
        lines.append("' Auto-generated by AutoForge Architecture Agent")
        lines.append("' Diagram type: UML Class Diagram")
        lines.append("skinparam classAttributeIconSize 0")
        lines.append("skinparam shadowing false")
        lines.append("hide empty members")
        lines.append("")
        lines.append(f"title {self._safe_label(title)}")
        lines.append("")

        for class_item in classes:
            lines.extend(self._class_block(class_item))
            lines.append("")

        for relationship in relationships:
            line = self._relationship_line(relationship)
            if line:
                lines.append(line)

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _class_block(self, class_item: dict[str, Any]) -> list[str]:
        class_id = self._safe_alias(class_item.get("id", class_item.get("name", "Class")))
        name = self._safe_label(class_item.get("name", class_id))
        stereotype = self._safe_label(class_item.get("stereotype", ""))
        attributes = class_item.get("attributes", []) or []
        operations = class_item.get("operations", []) or []

        header = f'class "{name}" as {class_id}'
        if stereotype:
            header += f" <<{stereotype}>>"
        header += " {"

        lines = [header]

        for attribute in attributes:
            if isinstance(attribute, dict):
                visibility = attribute.get("visibility", "+")
                attr_name = self._safe_member(attribute.get("name", "field"))
                attr_type = self._safe_member(attribute.get("type", "String"))
                lines.append(f"  {visibility}{attr_name}: {attr_type}")

        if attributes and operations:
            lines.append("  --")

        for operation in operations:
            if isinstance(operation, dict):
                visibility = operation.get("visibility", "+")
                op_name = self._safe_member(operation.get("name", "operation"))
                parameters = operation.get("parameters", []) or []
                return_type = self._safe_member(operation.get("return_type", "void"))
                param_text = ", ".join(self._safe_member(param) for param in parameters)
                lines.append(f"  {visibility}{op_name}({param_text}): {return_type}")

        lines.append("}")
        return lines

    def _relationship_line(self, relationship: dict[str, Any]) -> str | None:
        source = self._safe_alias(relationship.get("from", ""))
        target = self._safe_alias(relationship.get("to", ""))
        relation_type = str(relationship.get("type", "dependency")).lower().strip()
        label = self._safe_label(relationship.get("label", ""))

        if not source or not target:
            return None

        arrow = "..>"
        if relation_type == "association":
            arrow = "-->"
        elif relation_type == "aggregation":
            arrow = "o--"
        elif relation_type == "composition":
            arrow = "*--"
        elif relation_type in ["inheritance", "generalization"]:
            arrow = "--|>"
        elif relation_type == "dependency":
            arrow = "..>"

        # Standard UML cardinality notation on both ends -- only rendered
        # when both multiplicities are actually present (e.g. dependency/
        # inheritance/generalization never carry them), so this stays fully
        # backward compatible with a relationship that omits them.
        source_multiplicity = self._safe_label(relationship.get("source_multiplicity", ""))
        target_multiplicity = self._safe_label(relationship.get("target_multiplicity", ""))
        if source_multiplicity and target_multiplicity:
            endpoints = f'{source} "{source_multiplicity}" {arrow} "{target_multiplicity}" {target}'
        else:
            endpoints = f"{source} {arrow} {target}"

        if label:
            return f"{endpoints} : {label}"
        return endpoints

    def _safe_alias(self, value: str) -> str:
        value = str(value).strip()
        value = re.sub(r"[^a-zA-Z0-9_]", "_", value)
        if not value:
            return ""
        if value[0].isdigit():
            value = f"ID_{value}"
        return value

    def _safe_label(self, value: str) -> str:
        label = str(value).replace('"', "'").strip()
        label = re.sub(r"\s+", " ", label)
        return label

    def _safe_member(self, value: Any) -> str:
        text = str(value).strip()
        text = re.sub(r"[^a-zA-Z0-9_<>,\[\] ]", "", text)
        return text or "value"
