"""
Architecture Agent Architecture Plan PDF Builder.

Purpose:
Convert Architecture Plan JSON into a real, table-based HTML document
mirroring the frontend's own ArchitecturePlanDocumentViewer.jsx section order
-- Document Control; Feature Overview; Requirement Interpretation;
Architecture Approach; Frontend/Backend Architecture Plan; Implementation
Plan (backend files/endpoints/models, frontend pages/components/services/
routing, implementation order, constraints); API & Interface Plan; Data
Model Plan; Validation Plan; Error Handling Plan; Security Plan; Quality/NFR
Plan; Coder Implementation Tasks; Requirement-to-Architecture Traceability;
Assumptions/Constraints/Risks/Dependencies; Human Approval Note.

This is a NEW template, not a reuse of ArchitecturePlanMarkdownBuilder's
bulleted Markdown output.
"""

from __future__ import annotations

from typing import Any

from app.agents._shared.pdf_style import html_document_shell, signature_block_html
from app.agents.requirement_agent.pdf_builder import (
    _esc,
    _meta_table,
    _plain_list,
    _section,
    _smart_text_block,
    _text_block,
)

MAX_GENERIC_COLUMNS = 6


def _inline(value: Any) -> str:
    if isinstance(value, dict):
        return ", ".join(f"{k}: {_inline(v)}" for k, v in value.items())
    if isinstance(value, list):
        return ", ".join(_inline(v) for v in value)
    return str(value)


def _join(items: Any) -> str:
    if not items:
        return "N/A"
    if isinstance(items, list):
        return ", ".join(_inline(item) for item in items)
    return str(items)


def _generic_list(items: list[Any]) -> str:
    """
    Render an arbitrary list of records: a table when every item is a dict
    (columns = union of keys, in first-seen order, capped), otherwise a
    plain bullet list -- a robust fallback for the sub-lists whose exact
    shape can vary (e.g. design_views' less-structured sub-views).
    """
    if not items:
        return '<p class="empty-note">Not specified.</p>'

    if not all(isinstance(item, dict) for item in items):
        return _plain_list([_inline(item) for item in items])

    columns: list[str] = []
    for item in items:
        for key in item.keys():
            if key not in columns:
                columns.append(key)
    columns = columns[:MAX_GENERIC_COLUMNS]

    header = "".join(f"<th>{_esc(col.replace('_', ' ').title())}</th>" for col in columns)
    rows = []
    for item in items:
        cells = "".join(f"<td>{_esc(_inline(item.get(col, '')))}</td>" for col in columns)
        rows.append(f"<tr>{cells}</tr>")

    return f'<table class="data-table"><thead><tr>{header}</tr></thead><tbody>{"".join(rows)}</tbody></table>'


def _document_control_table(data: dict[str, Any]) -> str:
    rows = [
        ("Document Title", data.get("document_title", "N/A")),
        ("Document Type", data.get("document_type", "Feature Architecture Plan")),
        ("Project ID", data.get("project_id", "N/A")),
        ("Project Name", data.get("project_name", "N/A")),
        ("Project Type", data.get("project_type", "N/A")),
        ("Feature ID", data.get("feature_id", "N/A")),
        ("Feature Name", data.get("feature_name", "N/A")),
        ("Target Stack", data.get("target_stack", "N/A")),
        ("Architecture Style", data.get("architecture_style", "N/A")),
        ("Version", data.get("version", "v1")),
        ("Generated By", data.get("generated_by", "Architecture Agent")),
        ("Approval Status", data.get("approval_status", "pending")),
        ("Input Artifacts", _join(data.get("input_artifacts", []))),
    ]
    return _meta_table(rows)


def _feature_overview_html(data: dict[str, Any]) -> str:
    return (
        '<h3 class="subsection-title">Business Goal</h3>'
        + _smart_text_block(data.get("business_goal"))
        + '<h3 class="subsection-title">Scope</h3>'
        + _plain_list(data.get("scope", []))
        + '<h3 class="subsection-title">Out of Scope</h3>'
        + _plain_list(data.get("out_of_scope", []))
        + '<h3 class="subsection-title">User Roles</h3>'
        + _plain_list(data.get("user_roles", []))
        + '<h3 class="subsection-title">Feature Boundary</h3>'
        + _smart_text_block(data.get("feature_boundary"))
    )


def _requirement_interpretation_html(data: dict[str, Any]) -> str:
    return (
        '<h3 class="subsection-title">Functional Requirements Interpretation</h3>'
        + _generic_list(data.get("functional_requirements", []))
        + '<h3 class="subsection-title">Acceptance Criteria Interpretation</h3>'
        + _generic_list(data.get("acceptance_criteria", []))
        + '<h3 class="subsection-title">Validation Rules Interpretation</h3>'
        + _generic_list(data.get("validation_rules", []))
        + '<h3 class="subsection-title">Non-Functional Requirements Interpretation</h3>'
        + _generic_list(data.get("non_functional_requirements", []))
    )


def _architecture_approach_html(data: dict[str, Any]) -> str:
    return (
        # Architecture Style is a short label ("layered", "monolithic"), never multi-sentence
        # prose -- stays on the plain _text_block, unlike the fields below.
        '<h3 class="subsection-title">Architecture Style</h3>'
        + _text_block(data.get("architecture_style"))
        + '<h3 class="subsection-title">Architecture Rationale</h3>'
        + _smart_text_block(data.get("architecture_rationale"))
        + '<h3 class="subsection-title">Frontend Overview</h3>'
        + _smart_text_block(data.get("frontend_overview"))
        + '<h3 class="subsection-title">Backend Overview</h3>'
        + _smart_text_block(data.get("backend_overview"))
        + '<h3 class="subsection-title">Data Overview</h3>'
        + _smart_text_block(data.get("data_overview"))
        + '<h3 class="subsection-title">Integration Overview</h3>'
        + _smart_text_block(data.get("integration_overview"))
        + '<h3 class="subsection-title">Design Trade-offs</h3>'
        + _plain_list(data.get("design_tradeoffs", []))
    )


def _frontend_plan_html(data: dict[str, Any], design_views: dict[str, Any]) -> str:
    logical_view = design_views.get("logical_view", {})
    return (
        '<h3 class="subsection-title">Frontend Responsibilities</h3>'
        + _generic_list(data.get("responsibilities") or logical_view.get("frontend_modules", []))
        + '<h3 class="subsection-title">Pages / Components</h3>'
        + _generic_list(data.get("pages_or_components", []))
        + '<h3 class="subsection-title">State and User Feedback</h3>'
        + _plain_list(data.get("state_and_feedback", []))
    )


def _backend_plan_html(data: dict[str, Any], design_views: dict[str, Any]) -> str:
    logical_view = design_views.get("logical_view", {})
    layers = data.get("layers") or (
        logical_view.get("domain_services", []) + logical_view.get("data_modules", [])
    )
    return (
        '<h3 class="subsection-title">Backend Responsibilities</h3>'
        + _generic_list(data.get("responsibilities") or logical_view.get("backend_modules", []))
        + '<h3 class="subsection-title">Controller / Service / Data Responsibilities</h3>'
        + _generic_list(layers)
        + '<h3 class="subsection-title">Integration Points</h3>'
        + _generic_list(data.get("integration_points") or logical_view.get("integration_points", []))
    )


def _implementation_plan_html(data: dict[str, Any]) -> str:
    if not isinstance(data, dict) or not data:
        return '<p class="empty-note">Not specified.</p>'

    backend = data.get("backend", {}) or {}
    frontend = data.get("frontend", {}) or {}
    parts = []

    parts.append('<h3 class="subsection-title">Backend Files</h3>')
    files = backend.get("files", []) or []
    if files:
        rows = "".join(
            f"<tr><td>{_esc(item.get('path', ''))}</td><td>{_esc(item.get('action', ''))}</td>"
            f"<td>{_esc(item.get('purpose', ''))}</td></tr>"
            for item in files
            if isinstance(item, dict)
        )
        parts.append(
            '<table class="data-table"><thead><tr><th>Path</th><th>Action</th><th>Purpose</th></tr></thead>'
            f"<tbody>{rows}</tbody></table>"
        )
    else:
        parts.append('<p class="empty-note">None planned.</p>')

    parts.append('<h3 class="subsection-title">Endpoints</h3>')
    endpoints = backend.get("endpoints", []) or []
    if endpoints:
        rows = []
        for item in endpoints:
            if not isinstance(item, dict):
                continue
            fields = "; ".join(
                f"{f.get('field', '')} ({f.get('type', '')}, "
                f"{'required' if f.get('required') else 'optional'})"
                for f in item.get("request_body", []) or []
                if isinstance(f, dict)
            )
            errors = "; ".join(_inline(e) for e in item.get("error_cases", []) or [])
            rows.append(
                f"<tr><td>{_esc(item.get('method', ''))} {_esc(item.get('path', ''))}</td>"
                f"<td>{_esc(fields or '—')}</td><td>{_esc(item.get('response', '—'))}</td>"
                f"<td>{_esc(errors or '—')}</td></tr>"
            )
        parts.append(
            '<table class="data-table"><thead><tr><th>Endpoint</th><th>Request Fields</th>'
            f"<th>Response</th><th>Error Cases</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
        )
    else:
        parts.append('<p class="empty-note">None planned.</p>')

    parts.append('<h3 class="subsection-title">Data Models</h3>')
    models = backend.get("models", []) or []
    if models:
        rows = []
        for item in models:
            if not isinstance(item, dict):
                continue
            fields = "; ".join(
                f"{f.get('name', '')}: {f.get('type', '')} {f.get('constraints', '')}"
                for f in item.get("fields", []) or []
                if isinstance(f, dict)
            )
            rows.append(
                f"<tr><td>{_esc(item.get('name', ''))}</td><td>{_esc(item.get('file', ''))}</td>"
                f"<td>{_esc(fields or '—')}</td></tr>"
            )
        parts.append(
            '<table class="data-table"><thead><tr><th>Name</th><th>File</th><th>Fields</th></tr></thead>'
            f"<tbody>{''.join(rows)}</tbody></table>"
        )
    else:
        parts.append('<p class="empty-note">None planned.</p>')

    parts.append('<h3 class="subsection-title">Frontend Pages / Components / Services</h3>')
    fe_lines: list[str] = []
    for page in frontend.get("pages", []) or []:
        if isinstance(page, dict):
            fe_lines.append(
                f"Page {page.get('path', '')} at route {page.get('route', '')}: {page.get('purpose', '')}"
            )
    for component in frontend.get("components_to_reuse", []) or []:
        fe_lines.append(f"Reuse approved component: {_inline(component)}")
    for service in frontend.get("services", []) or []:
        if isinstance(service, dict):
            functions = ", ".join(
                f"{f.get('name', '')} -> {f.get('calls_endpoint', '')}"
                for f in service.get("functions", []) or []
                if isinstance(f, dict)
            )
            fe_lines.append(f"Service {service.get('path', '')}: {functions or 'no functions listed'}")
    routing = frontend.get("routing", {}) or {}
    for route in routing.get("new_routes", []) or []:
        fe_lines.append(f"Route: {_inline(route)}")
    for link in routing.get("nav_links", []) or []:
        fe_lines.append(f"Nav link: {_inline(link)}")
    parts.append(_plain_list(fe_lines))

    parts.append('<h3 class="subsection-title">Implementation Order</h3>')
    order = data.get("implementation_order", []) or []
    if order:
        items = "".join(f"<li>{_esc(_inline(step))}</li>" for step in order)
        parts.append(f'<ol class="plain-list">{items}</ol>')
    else:
        parts.append('<p class="empty-note">Not specified.</p>')

    parts.append('<h3 class="subsection-title">Constraints</h3>')
    parts.append(_plain_list(data.get("constraints", []) or []))

    return "".join(parts)


def _interface_view_html(data: dict[str, Any]) -> str:
    endpoints = data.get("api_endpoints", []) or []
    if endpoints:
        rows = []
        for endpoint in endpoints:
            if not isinstance(endpoint, dict):
                rows.append(f"<tr><td colspan='5'>{_esc(endpoint)}</td></tr>")
                continue
            rows.append(
                f"<tr><td>{_esc(endpoint.get('method', 'METHOD'))} {_esc(endpoint.get('endpoint', '/path'))}</td>"
                f"<td>{_esc(endpoint.get('purpose', ''))}</td>"
                f"<td>{_esc(endpoint.get('request_model', 'N/A'))}</td>"
                f"<td>{_esc(endpoint.get('success_response_model', 'N/A'))}</td>"
                f"<td>{_esc(_join(endpoint.get('related_requirements', [])))}</td></tr>"
            )
        endpoints_html = (
            '<table class="data-table"><thead><tr><th>Endpoint</th><th>Purpose</th>'
            "<th>Request Model</th><th>Response Model</th><th>Related Requirements</th></tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table>"
        )
    else:
        endpoints_html = '<p class="empty-note">Not specified.</p>'

    def _models_html(models: list[Any]) -> str:
        if not models:
            return '<p class="empty-note">Not specified.</p>'
        rows = []
        for model in models:
            if not isinstance(model, dict):
                rows.append(f"<tr><td colspan='3'>{_esc(model)}</td></tr>")
                continue
            fields = _join(model.get("fields", []))
            rows.append(
                f"<tr><td>{_esc(model.get('name', 'Model'))}</td><td>{_esc(fields)}</td>"
                f"<td>{_esc(_join(model.get('related_requirements', [])))}</td></tr>"
            )
        return (
            '<table class="data-table"><thead><tr><th>Model</th><th>Fields</th>'
            f"<th>Related Requirements</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
        )

    return (
        '<h3 class="subsection-title">API Endpoints</h3>'
        + endpoints_html
        + '<h3 class="subsection-title">Request Models</h3>'
        + _models_html(data.get("request_models", []))
        + '<h3 class="subsection-title">Response Models</h3>'
        + _models_html(data.get("response_models", []))
    )


def _data_view_html(data: dict[str, Any]) -> str:
    entities = data.get("data_entities", []) or []
    if entities:
        rows = []
        for entity in entities:
            if not isinstance(entity, dict):
                rows.append(f"<tr><td colspan='4'>{_esc(entity)}</td></tr>")
                continue
            rows.append(
                f"<tr><td>{_esc(entity.get('name', 'Entity'))}</td>"
                f"<td>{_esc(entity.get('purpose', ''))}</td>"
                f"<td>{_esc(_join(entity.get('fields', [])))}</td>"
                f"<td>{_esc(_join(entity.get('related_requirements', [])))}</td></tr>"
            )
        entities_html = (
            '<table class="data-table"><thead><tr><th>Entity</th><th>Purpose</th><th>Fields</th>'
            f"<th>Related Requirements</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
        )
    else:
        entities_html = '<p class="empty-note">Not specified.</p>'

    return (
        '<h3 class="subsection-title">Data Entities</h3>'
        + entities_html
        + '<h3 class="subsection-title">Storage Rules</h3>'
        + _plain_list(data.get("storage_rules", []))
        + '<h3 class="subsection-title">Data Validation Rules</h3>'
        + _generic_list(data.get("data_validation_rules", []))
    )


def _validation_plan_html(data: dict[str, Any], design_views: dict[str, Any]) -> str:
    data_view = design_views.get("data_view", {})
    return (
        '<h3 class="subsection-title">Input Validation Rules</h3>'
        + _generic_list(data.get("input_validation") or data_view.get("data_validation_rules", []))
        + '<h3 class="subsection-title">Processing Validation Rules</h3>'
        + _generic_list(data.get("processing_validation", []))
    )


def _error_handling_html(data: dict[str, Any]) -> str:
    return (
        '<h3 class="subsection-title">Validation Errors</h3>'
        + _generic_list(data.get("validation_errors", []))
        + '<h3 class="subsection-title">Business Errors</h3>'
        + _generic_list(data.get("business_errors", []))
        + '<h3 class="subsection-title">Authorization Errors</h3>'
        + _generic_list(data.get("authorization_errors", []))
        + '<h3 class="subsection-title">System Errors</h3>'
        + _generic_list(data.get("system_errors", []))
        + '<h3 class="subsection-title">User Message Rules</h3>'
        + _plain_list(data.get("user_message_rules", []))
    )


def _security_view_html(data: dict[str, Any]) -> str:
    return (
        '<h3 class="subsection-title">Authentication Design</h3>'
        + _generic_list(data.get("authentication_design", []))
        + '<h3 class="subsection-title">Authorization Design</h3>'
        + _generic_list(data.get("authorization_design", []))
        + '<h3 class="subsection-title">Sensitive Data Rules</h3>'
        + _generic_list(data.get("sensitive_data_rules", []))
        + '<h3 class="subsection-title">Risk Mitigations</h3>'
        + _generic_list(data.get("risk_mitigations", []))
    )


def _quality_view_html(data: dict[str, Any]) -> str:
    parts = []
    for key, title in [
        ("performance", "Performance"),
        ("usability", "Usability"),
        ("reliability", "Reliability"),
        ("scalability", "Scalability"),
        ("maintainability", "Maintainability"),
        ("accessibility", "Accessibility"),
    ]:
        parts.append(f'<h3 class="subsection-title">{title}</h3>')
        parts.append(_generic_list(data.get(key, [])))
    return "".join(parts)


def _implementation_tasks_html(tasks: list[Any]) -> str:
    if not tasks:
        return '<p class="empty-note">Not specified.</p>'
    rows = []
    for task in tasks:
        if not isinstance(task, dict):
            rows.append(f"<tr><td colspan='4'>{_esc(task)}</td></tr>")
            continue
        rows.append(
            f"<tr><td>{_esc(task.get('task_id', 'TASK'))}</td>"
            f"<td>{_esc(task.get('task', task.get('description', 'Not specified.')))}</td>"
            f"<td>{_esc(task.get('layer', 'N/A'))}</td>"
            f"<td>{_esc(_join(task.get('suggested_files', [])))}</td></tr>"
        )
    return (
        '<table class="data-table"><thead><tr><th>Task ID</th><th>Task</th><th>Layer</th>'
        f"<th>Suggested Files</th></tr></thead><tbody>{''.join(rows)}</tbody></table>"
    )


def _traceability_matrix_html(items: list[Any]) -> str:
    if not items:
        return '<p class="empty-note">Not specified.</p>'
    rows = []
    for item in items:
        if not isinstance(item, dict):
            continue
        section = item.get("architecture_plan_section") or item.get("sds_section") or "N/A"
        element = item.get("design_element") or item.get("task") or "N/A"
        rows.append(
            f"<tr><td>{_esc(item.get('source_id', 'N/A'))}</td><td>{_esc(item.get('source_type', 'N/A'))}</td>"
            f"<td>{_esc(section)}</td><td>{_esc(element)}</td>"
            f"<td>{_esc(item.get('coverage_status', 'covered'))}</td></tr>"
        )
    return (
        '<table class="data-table"><thead><tr><th>Source ID</th><th>Source Type</th>'
        "<th>Architecture Plan Section</th><th>Design / Task Element</th><th>Coverage</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def build_architecture_plan_html(architecture_plan_json: dict[str, Any]) -> str:
    """
    Build a complete, self-contained Architecture Plan HTML document.
    """
    document_control = architecture_plan_json.get("document_control", {})
    feature_overview = architecture_plan_json.get("feature_overview", {})
    requirement_interpretation = architecture_plan_json.get("requirement_interpretation", {})
    architecture_approach = architecture_plan_json.get("architecture_approach", {})
    design_views = architecture_plan_json.get("design_views", {})

    feature_name = (
        document_control.get("feature_name")
        or architecture_plan_json.get("feature_name")
        or "Untitled Feature"
    )

    sections = [
        _section(1, "Document Control", _document_control_table(document_control)),
        _section(2, "Feature Overview", _feature_overview_html(feature_overview)),
        _section(3, "Requirement Interpretation", _requirement_interpretation_html(requirement_interpretation)),
        _section(4, "Architecture Approach", _architecture_approach_html(architecture_approach)),
        _section(
            5,
            "Frontend Architecture Plan",
            _frontend_plan_html(architecture_plan_json.get("frontend_architecture_plan", {}), design_views),
        ),
        _section(
            6,
            "Backend Architecture Plan",
            _backend_plan_html(architecture_plan_json.get("backend_architecture_plan", {}), design_views),
        ),
        _section(
            7,
            "End-to-End Implementation Plan (Coder Agent Blueprint)",
            _implementation_plan_html(architecture_plan_json.get("implementation_plan", {})),
        ),
        _section(8, "API and Interface Plan", _interface_view_html(design_views.get("interface_view", {}))),
        _section(9, "Data Model Plan", _data_view_html(design_views.get("data_view", {}))),
        _section(
            10,
            "Validation Plan",
            _validation_plan_html(architecture_plan_json.get("validation_plan", {}), design_views),
        ),
        _section(11, "Error Handling Plan", _error_handling_html(design_views.get("error_handling_view", {}))),
        _section(12, "Security Plan", _security_view_html(design_views.get("security_authorization_view", {}))),
        _section(13, "Quality / NFR Plan", _quality_view_html(design_views.get("quality_attributes_view", {}))),
        _section(
            14, "Coder Implementation Tasks", _implementation_tasks_html(architecture_plan_json.get("coder_implementation_tasks", []))
        ),
        _section(
            15,
            "Requirement-to-Architecture Traceability",
            _traceability_matrix_html(architecture_plan_json.get("traceability_matrix", [])),
        ),
        _section(
            16,
            "Assumptions, Constraints, Risks, and Dependencies",
            '<h3 class="subsection-title">Assumptions</h3>'
            + _plain_list(architecture_plan_json.get("assumptions", []))
            + '<h3 class="subsection-title">Constraints</h3>'
            + _plain_list(architecture_plan_json.get("constraints", []))
            + '<h3 class="subsection-title">Risks</h3>'
            + _generic_list(architecture_plan_json.get("risks", []))
            + '<h3 class="subsection-title">Dependencies</h3>'
            + _plain_list(architecture_plan_json.get("dependencies", [])),
        ),
        _section(
            17,
            "Human Approval Note",
            _smart_text_block(
                architecture_plan_json.get(
                    "human_approval_note",
                    "This Architecture Plan must be reviewed and approved before the UI/UX "
                    "Agent or Coder Agent starts.",
                )
            ),
        ),
        _section(18, "Document Sign-Off", signature_block_html()),
    ]

    body_html = "".join(sections)
    body_html += (
        '<div class="doc-footer">Generated by AutoForge -- Architecture Agent. '
        "This document is a formatted export of the underlying Architecture Plan artifact.</div>"
    )

    return html_document_shell(
        title=f"Architecture Plan: {feature_name}",
        subtitle="Architecture Agent -- Feature-level Architecture Plan",
        body_html=body_html,
    )
