"""
Architecture Agent Sequence Diagram PlantUML Builder.

Purpose:
Convert validated sequence_diagram_json into PlantUML sequence diagram source.

Rules applied:
- Actor lifelines use actor notation.
- Boundary/control/entity/database/external participants use UML stereotypes.
- Messages are rendered in the provided order.
- Return messages use dashed arrows; async messages use an open arrowhead.
- Optional/alternative/error/repeated/concurrent/early-exit flows are rendered using UML combined
  fragments (alt/opt/loop/par/break).
"""

from __future__ import annotations

import re
from typing import Any

from app.agents.architecture_agent.sequence_fragment_kinds import ALL_INTERACTION_KINDS
from app.utils.logger import get_logger

logger = get_logger(__name__)


class ArchitectureSequencePlantUMLBuilder:
    """
    Converts sequence_diagram_json into PlantUML source.
    """

    def build(self, sequence_json: dict[str, Any]) -> str:
        title = sequence_json.get("diagram_title", "Sequence Diagram")
        participants = sequence_json.get("participants", [])
        interactions = sequence_json.get("interactions", [])

        lines: list[str] = []
        lines.append("@startuml")
        lines.append("' Auto-generated by AutoForge Architecture Agent")
        lines.append("' Diagram type: UML Sequence Diagram")
        lines.append("skinparam shadowing false")
        lines.append("skinparam sequenceMessageAlign center")
        lines.append("")
        lines.append(f"title {self._safe_label(title)}")
        lines.append("")

        for participant in participants:
            line = self._participant_line(participant)
            if line:
                lines.append(line)

        lines.append("")

        for interaction in interactions:
            kind = str(interaction.get("kind", "message"))

            if kind == "message":
                message_line = self._message_line(interaction)
                if message_line:
                    lines.append(message_line)
                continue

            if kind == "alt_start":
                condition = self._safe_label(interaction.get("condition", "Alternative"))
                lines.append(f"alt {condition}")
                continue

            if kind == "opt_start":
                condition = self._safe_label(interaction.get("condition", "Optional"))
                lines.append(f"opt {condition}")
                continue

            if kind == "loop_start":
                condition = self._safe_label(interaction.get("condition", "Repeat"))
                lines.append(f"loop {condition}")
                continue

            if kind == "par_start":
                condition = self._safe_label(interaction.get("condition", "Concurrent"))
                lines.append(f"par {condition}")
                continue

            if kind == "break_start":
                condition = self._safe_label(interaction.get("condition", "Break"))
                lines.append(f"break {condition}")
                continue

            if kind == "else":
                condition = self._safe_label(interaction.get("condition", "Else"))
                lines.append(f"else {condition}")
                continue

            if kind == "end":
                lines.append("end")
                continue

            # Anything else is a genuinely unrecognized kind -- previously silently dropped here
            # with no trace, while sequence_validator.py would separately reject it as "Invalid
            # sequence interaction kind" if it ever reached that stage (a real, confirmed
            # inconsistency). Both files now import ALL_INTERACTION_KINDS from the same shared
            # module, so this branch should be unreachable in practice; logging instead of
            # silently continuing makes it visible immediately if that ever drifts.
            if kind not in ALL_INTERACTION_KINDS:
                logger.warning("Skipping unrecognized sequence interaction kind: %s", kind)

        lines.append("")
        lines.append("@enduml")
        return "\n".join(lines)

    def _participant_line(self, participant: dict[str, Any]) -> str | None:
        participant_id = self._safe_alias(participant.get("id", ""))
        name = self._safe_label(participant.get("name", participant_id))
        participant_type = str(participant.get("type", "participant")).lower()

        if not participant_id or not name:
            return None

        if participant_type == "actor":
            return f'actor "{name}" as {participant_id}'
        if participant_type == "boundary":
            return f'boundary "{name}" as {participant_id}'
        if participant_type == "control":
            return f'control "{name}" as {participant_id}'
        if participant_type == "entity":
            return f'entity "{name}" as {participant_id}'
        if participant_type == "database":
            return f'database "{name}" as {participant_id}'
        if participant_type == "external":
            return f'participant "{name}" as {participant_id} <<external>>'

        return f'participant "{name}" as {participant_id}'

    def _message_line(self, interaction: dict[str, Any]) -> str | None:
        source = self._safe_alias(interaction.get("from", ""))
        target = self._safe_alias(interaction.get("to", ""))
        message = self._safe_label(interaction.get("message", "message"))
        message_type = str(interaction.get("message_type", "sync")).lower()

        if not source or not target:
            return None

        if source == target or message_type == "self":
            return f"{source} -> {target}: {message}"

        if message_type == "async":
            arrow = "->>"
        elif message_type == "return":
            arrow = "-->"
        else:
            arrow = "->"
        return f"{source} {arrow} {target}: {message}"

    def _safe_alias(self, value: str) -> str:
        value = str(value).strip()
        value = re.sub(r"[^a-zA-Z0-9_]", "_", value)
        if not value:
            return ""
        if value[0].isdigit():
            value = f"ID_{value}"
        return value

    def _safe_label(self, value: str) -> str:
        label = str(value).replace('"', "'").strip()
        label = re.sub(r"\s+", " ", label)
        if len(label) > 100:
            label = label[:97].rstrip() + "..."
        return label
