"""
Architecture Agent Use Case Diagram Builder.

Purpose:
Convert a validated usecase_json model into PlantUML source.

Important:
- The LLM must not directly generate PlantUML.
- This builder only draws the already validated model.
- The diagram is kept as a standard UML Use Case Diagram:
  actors + system boundary + use cases + relationships.
- Constraints, NFRs, risks, and SDS design notes are intentionally NOT rendered
  as notes in the use case diagram. They belong in the SDS, not in the UML
  Use Case Diagram artifact.
"""

from __future__ import annotations

import re
from typing import Any


class ArchitectureUseCasePlantUMLBuilder:
    """
    Converts usecase_json into clean PlantUML use case diagram source.
    """

    def build(self, usecase_json: dict[str, Any]) -> str:
        """
        Build PlantUML source from validated usecase_json.
        """

        diagram_title = usecase_json.get("diagram_title", "Use Case Diagram")
        system_boundary = usecase_json.get("system_boundary", "Feature System")

        actors = usecase_json.get("actors", [])
        use_cases = usecase_json.get("use_cases", [])
        relationships = usecase_json.get("relationships", [])

        lines: list[str] = []

        lines.append("@startuml")
        lines.append("' Auto-generated by AutoForge Architecture Agent")
        lines.append("' Diagram type: UML Use Case Diagram")
        lines.append("left to right direction")
        lines.append("skinparam packageStyle rectangle")
        lines.append("skinparam shadowing false")
        lines.append("")
        lines.append(f"title {self._safe_label(diagram_title)}")
        lines.append("")

        # Actors must stay outside the system boundary.
        for actor in actors:
            actor_id = self._safe_alias(actor.get("id", actor.get("name", "ACT")))
            actor_name = self._safe_label(actor.get("name", actor_id))
            # <<external system>> marks a non-human/external-system actor (agilemodeling.com's
            # own "use a stereotype to indicate a non-human actor" rule, rendered with an
            # explicit, unambiguous label rather than the bare word "system" -- a real reviewer
            # flagged the bare tag as unclear); a real, human user role gets no stereotype suffix.
            stereotype_suffix = " <<external system>>" if str(actor.get("stereotype", "")).strip().lower() == "system" else ""
            lines.append(f'actor "{actor_name}" as {actor_id}{stereotype_suffix}')

        lines.append("")

        # Use cases must stay inside the system boundary.
        lines.append(f'rectangle "{self._safe_label(system_boundary)}" {{')

        for use_case in use_cases:
            uc_id = self._safe_alias(use_case.get("id", use_case.get("name", "UC")))
            uc_name = self._safe_label(use_case.get("name", uc_id))
            lines.append(f'  usecase "{uc_name}" as {uc_id}')

        lines.append("}")
        lines.append("")

        # Relationships are drawn after declarations.
        for relationship in relationships:
            relation_line = self._build_relationship(relationship)
            if relation_line:
                lines.append(relation_line)

        lines.append("")
        lines.append("@enduml")

        return "\n".join(lines)

    def _build_relationship(self, relationship: dict[str, Any]) -> str | None:
        """
        Convert one relationship object into PlantUML syntax.

        Supported types:
        - association: actor -- use case
        - include: base use case .> included use case : <<include>>
        - extend: extension use case .> base use case : <<extend>>
        - generalization: child --|> parent
        """

        source = self._safe_alias(relationship.get("from", ""))
        target = self._safe_alias(relationship.get("to", ""))
        relation_type = str(relationship.get("type", "association")).lower().strip()
        label = str(relationship.get("label", "")).strip()

        if not source or not target:
            return None

        if relation_type == "association":
            if label:
                return f"{source} -- {target} : {self._safe_label(label)}"
            return f"{source} -- {target}"

        if relation_type == "include":
            return f"{source} .> {target} : <<include>>"

        if relation_type == "extend":
            return f"{source} .> {target} : <<extend>>"

        if relation_type == "generalization":
            return f"{source} --|> {target}"

        return None

    def _safe_alias(self, value: str) -> str:
        """
        Convert actor/use case ID into a PlantUML-safe alias.
        """

        value = str(value).strip()
        value = re.sub(r"[^a-zA-Z0-9_]", "_", value)

        if not value:
            value = "UNKNOWN"

        if value[0].isdigit():
            value = f"ID_{value}"

        return value

    def _safe_label(self, value: str) -> str:
        """
        Escape unsafe characters and keep diagram labels readable.
        """

        label = str(value).replace('"', "'").strip()
        label = re.sub(r"\s+", " ", label)

        # Use case names should already be short. This is a final safety guard.
        if len(label) > 70:
            label = label[:67].rstrip() + "..."

        return label
