"""
Unit tests for the Next.js scaffold's PreviewRouteAnnouncer wiring (the
postMessage-based mechanism that lets the Live Preview panel's displayed URL
track in-iframe navigation, since the preview iframe is genuinely
cross-origin -- see PreviewPanel.jsx) and its idempotent upgrade path for a
project scaffolded before this component existed.

Real git repos (same fixture/teardown convention as
test_workspace_nextjs_tailwind.py), no LLM/Docker.
"""

import os
import shutil
import stat

import pytest

from app.services.in_memory_store import store
from app.services.workspace_service import NEXTJS_SCAFFOLD_FILES, workspace_service
from app.utils.id_generator import generate_id


def _remove_readonly(func, path, _exc_info):
    os.chmod(path, stat.S_IWRITE)
    func(path)


@pytest.fixture
def project_id():
    pid = generate_id("project")
    store.projects[pid] = {"project_id": pid, "project_name": f"Preview Announcer Test {pid}"}

    yield pid

    repo_path = workspace_service.get_repo_path(pid)
    if (repo_path / ".git").exists():
        workspace_service.ensure_project_repo(pid).close()
    store.database["projects"].delete_one({"project_id": pid})
    if repo_path.parent.exists():
        shutil.rmtree(repo_path.parent, onerror=_remove_readonly)


def test_fresh_project_has_preview_route_announcer_component(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)

    assert "components/PreviewRouteAnnouncer.tsx" in NEXTJS_SCAFFOLD_FILES
    announcer_path = repo_path / "components" / "PreviewRouteAnnouncer.tsx"
    assert announcer_path.exists()

    content = announcer_path.read_text(encoding="utf-8")
    assert "usePathname" in content
    assert "autoforge-preview-route" in content
    assert "window.parent.postMessage" in content


def test_fresh_project_layout_mounts_the_announcer(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)

    layout = (repo_path / "app" / "layout.tsx").read_text(encoding="utf-8")
    assert "PreviewRouteAnnouncer" in layout
    assert '"@/components/PreviewRouteAnnouncer"' in layout


def test_upgrade_backfill_adds_the_announcer_to_a_pre_existing_stock_layout(project_id):
    """
    Simulates a real, already-scaffolded (pre-announcer) Next.js project by
    stripping the announcer's import/mount back out of an otherwise-stock
    layout.tsx, then confirming a second ensure_project_repo call (the real
    retrofit path every scaffold upgrade in this project uses) restores it.
    """
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)
    repo = workspace_service.ensure_project_repo(project_id)

    announcer_path = repo_path / "components" / "PreviewRouteAnnouncer.tsx"
    announcer_path.unlink()

    layout_path = repo_path / "app" / "layout.tsx"
    layout_path.write_text(
        (
            'import type { Metadata } from "next";\n'
            'import "./globals.css";\n\n'
            'export const metadata: Metadata = {\n'
            '  title: "Auto-Forge Generated App",\n'
            '  description: "Generated by Auto-Forge MAS",\n'
            "};\n\n"
            "export default function RootLayout({\n"
            "  children,\n"
            "}: Readonly<{\n"
            "  children: React.ReactNode;\n"
            "}>) {\n"
            "  return (\n"
            '    <html lang="en">\n'
            "      <body>{children}</body>\n"
            "    </html>\n"
            "  );\n"
            "}\n"
        ),
        encoding="utf-8",
    )

    repo.git.add(A=True)
    repo.index.commit("Simulate a pre-announcer project state")

    workspace_service.ensure_project_repo(project_id)

    assert announcer_path.exists()
    layout = layout_path.read_text(encoding="utf-8")
    assert "PreviewRouteAnnouncer" in layout
    # The persistent nav/footer backfill (test_workspace_preview_route_announcer.py's own
    # dedicated cases below) runs in the same ensure_project_repo call right after this one, so
    # {children} ends up wrapped in <main> with a header/footer around it rather than sitting
    # bare inside <body> -- confirm the announcer mount landed correctly, not the old exact
    # pre-nav-footer body shape.
    assert "<PreviewRouteAnnouncer />" in layout
    assert "<main>{children}</main>" in layout


def test_upgrade_backfill_never_touches_a_layout_customized_past_recognition(project_id):
    """
    A real, confirmed case (the live nextjs-migration-verify project): once a
    feature has restructured <body>{children}</body> (e.g. wrapping it with
    its own <Navbar>/<Footer>), the exact anchor this upgrade requires no
    longer exists. It must no-op (log a warning) rather than guess at an
    insertion point and risk corrupting the file.
    """
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)
    repo = workspace_service.ensure_project_repo(project_id)

    announcer_path = repo_path / "components" / "PreviewRouteAnnouncer.tsx"
    announcer_path.unlink()

    layout_path = repo_path / "app" / "layout.tsx"
    customized_layout = (
        'import type { Metadata } from "next";\n'
        'import "./globals.css";\n'
        'import Navbar from "@/components/Navbar";\n\n'
        'export const metadata: Metadata = {\n'
        '  title: "Auto-Forge Generated App",\n'
        '  description: "Generated by Auto-Forge MAS",\n'
        "};\n\n"
        "export default function RootLayout({\n"
        "  children,\n"
        "}: Readonly<{\n"
        "  children: React.ReactNode;\n"
        "}>) {\n"
        "  return (\n"
        '    <html lang="en">\n'
        "      <body>\n"
        "        <Navbar />\n"
        "        <main>{children}</main>\n"
        "      </body>\n"
        "    </html>\n"
        "  );\n"
        "}\n"
    )
    layout_path.write_text(customized_layout, encoding="utf-8")

    repo.git.add(A=True)
    repo.index.commit("Simulate a layout customized past recognition")

    workspace_service.ensure_project_repo(project_id)

    # The component itself is still backfilled (a missing file is safe to add)...
    assert announcer_path.exists()
    # ...but the customized layout is left completely untouched -- no partial
    # insertion, no corruption.
    assert layout_path.read_text(encoding="utf-8") == customized_layout


def test_upgrade_backfill_is_idempotent_when_announcer_already_present(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo = workspace_service.ensure_project_repo(project_id)
    before_sha = repo.head.commit.hexsha

    workspace_service.ensure_project_repo(project_id)
    repo_after = workspace_service.ensure_project_repo(project_id)

    assert repo_after.head.commit.hexsha == before_sha
    assert not repo_after.is_dirty(untracked_files=True)


def test_fresh_project_layout_has_persistent_nav_footer(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)

    layout = (repo_path / "app" / "layout.tsx").read_text(encoding="utf-8")
    assert "<header" in layout
    assert "<footer" in layout
    assert 'Link href="/"' in layout
    assert "export const viewport" in layout


def test_upgrade_backfill_adds_nav_footer_to_a_pre_upgrade_layout(project_id):
    """
    Simulates a real project scaffolded after PreviewRouteAnnouncer existed but before the
    persistent nav/footer upgrade -- confirms a second ensure_project_repo call backfills the
    header/footer around {children} without disturbing the announcer mount.
    """
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)
    repo = workspace_service.ensure_project_repo(project_id)

    layout_path = repo_path / "app" / "layout.tsx"
    pre_upgrade_layout = (
        'import type { Metadata } from "next";\n'
        'import "./globals.css";\n'
        'import PreviewRouteAnnouncer from "@/components/PreviewRouteAnnouncer";\n\n'
        'export const metadata: Metadata = {\n'
        '  title: "Auto-Forge Generated App",\n'
        '  description: "Generated by Auto-Forge MAS",\n'
        "};\n\n"
        "export default function RootLayout({\n"
        "  children,\n"
        "}: Readonly<{\n"
        "  children: React.ReactNode;\n"
        "}>) {\n"
        "  return (\n"
        '    <html lang="en">\n'
        "      <body>\n"
        "        <PreviewRouteAnnouncer />\n"
        "        {children}\n"
        "      </body>\n"
        "    </html>\n"
        "  );\n"
        "}\n"
    )
    layout_path.write_text(pre_upgrade_layout, encoding="utf-8")

    repo.git.add(A=True)
    repo.index.commit("Simulate a pre-nav-footer project state")

    workspace_service.ensure_project_repo(project_id)

    layout = layout_path.read_text(encoding="utf-8")
    assert "PreviewRouteAnnouncer" in layout
    assert "<header" in layout
    assert "<footer" in layout
    assert 'import Link from "next/link";' in layout


def test_upgrade_backfill_nav_footer_never_touches_a_layout_customized_past_recognition(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo_path = workspace_service.get_repo_path(project_id)
    repo = workspace_service.ensure_project_repo(project_id)

    layout_path = repo_path / "app" / "layout.tsx"
    customized_layout = (
        'import type { Metadata } from "next";\n'
        'import "./globals.css";\n'
        'import PreviewRouteAnnouncer from "@/components/PreviewRouteAnnouncer";\n'
        'import Navbar from "@/components/Navbar";\n\n'
        'export const metadata: Metadata = {\n'
        '  title: "Auto-Forge Generated App",\n'
        '  description: "Generated by Auto-Forge MAS",\n'
        "};\n\n"
        "export default function RootLayout({\n"
        "  children,\n"
        "}: Readonly<{\n"
        "  children: React.ReactNode;\n"
        "}>) {\n"
        "  return (\n"
        '    <html lang="en">\n'
        "      <body>\n"
        "        <PreviewRouteAnnouncer />\n"
        "        <Navbar />\n"
        "        <main>{children}</main>\n"
        "      </body>\n"
        "    </html>\n"
        "  );\n"
        "}\n"
    )
    layout_path.write_text(customized_layout, encoding="utf-8")

    repo.git.add(A=True)
    repo.index.commit("Simulate a layout customized past recognition, post-announcer")

    workspace_service.ensure_project_repo(project_id)

    assert layout_path.read_text(encoding="utf-8") == customized_layout


def test_upgrade_backfill_nav_footer_is_idempotent_when_header_already_present(project_id):
    workspace_service.ensure_project_repo(project_id)
    repo = workspace_service.ensure_project_repo(project_id)
    before_sha = repo.head.commit.hexsha

    workspace_service.ensure_project_repo(project_id)
    repo_after = workspace_service.ensure_project_repo(project_id)

    assert repo_after.head.commit.hexsha == before_sha
    assert not repo_after.is_dirty(untracked_files=True)
